### ISSUE TITLE
In insert mode the highlight is not updated

### ISSUE THREAD

**Issue by basilgood** [pocke/iro.vim#11]
Hi, thanks for your great work. I like a lot this plugin. I'm working a lot in yaml and your plugin make the best higlighting syntax from all plugins. But when in insert mode it's not update the syntax. The text appear white and are not highlighting but only when living insert mode with <ESC> or hit <C-o>. It's a pity because a mistake is not show before I finish to write and switch to normal mode.

**Comment by pocke** [comment]
Hi. Thank you for the feedback!

> In insert mode the highlight is not updated

I opened a pull-request for this problem. #12
It looks working well to me, but maybe the change has a performance issue. Because `TextChangedi` event occurs many times while editing, and `iro#redraw()` is not pretty fast.
So, can you try this pull-request? If it does not have performance issue, I'll merge it. Unfortunately if it has performance issue, I'll try other solutions (e.g. make it to optional, make it faster, ...).

**Comment by basilgood** [comment]
Hi. Thank you for the quick response.
I haven't any performance issue. It works pretty well for me too.
I like a lot the plugin behavior.
I think it's a great and very useful idea.
